#ifndef SSEST_VERSION_INCLUDED
#define SSEST_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define SSEST_VERSION_MAJOR 1
#define SSEST_VERSION_MINOR 0
#define SSEST_VERSION_PATCH 0
#define SSEST_VERSION_BETA 0
#define SSEST_VERSION_VERSTRING   \
	MAKE_STR(SSEST_VERSION_MAJOR) \
	"." MAKE_STR(SSEST_VERSION_MINOR) "." MAKE_STR(SSEST_VERSION_PATCH) "." MAKE_STR(SSEST_VERSION_BETA)

#endif
